version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop-rabbitmq
    restart: unless-stopped  
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro 
    networks:
      - shop-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s  
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s

  shop-service:
    build:
      context: ./shop-service
    container_name: shop-service
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shop-network

volumes:
  rabbitmq_data:

networks:
  shop-network:
    driver: bridge
